project_id = "yupqrawkrpyfrdzxssdk"

[functions.reset-demo-passwords]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.handle-fd-request]
verify_jwt = false

[functions.get-available-fds]
verify_jwt = false

[functions.create-fd-request]
verify_jwt = false