project_id = "yupqrawkrpyfrdzxssdk"

[functions.register-professional]
verify_jwt = false

[functions.reset-demo-passwords]
verify_jwt = false

[functions.create-pending-fd]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.handle-fd-request]
verify_jwt = false

[functions.get-available-fds]
verify_jwt = false

[functions.create-fd-request]
verify_jwt = false

[functions.send-org-decision-email]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.invite-info]
verify_jwt = false

[functions.accept-invite]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.public-mosque-feed]
verify_jwt = false

[functions.seed-dossier-tasks]
verify_jwt = false

